### ISSUE TITLE
A mistake in the README.md

### ISSUE THREAD

**Issue by whyliam** [jillix/jQuery-image-upload#14]
In the README.md file, at chapter [Event](https://github.com/jillix/jQuery-image-upload/blob/master/README.md#events), You write two `imageUpload.imageChanged`.

![](http://ww3.sinaimg.cn/large/48910e01gw1etp5g0xe4lj21c00j2djh.jpg)

**Comment by IonicaBizau** [comment]
@liszd Thanks for the heads-up! Fixed. :cake:
